# Action definition for the GitHub Accurics Action
name: 'Accurics GitHub Action'
author: 'accurics'
description: 'An action that performs a scan using the Accurics platform'
branding:
  color: blue
  icon: shield
inputs:
  debug-mode:
    required: false
    default: false
  terraform-version:
    description: 'The Terraform version used to process the files in this repository (ex: 0.12.26). (default=latest)'
    required: false
    default: 'latest'
  directories:
    description: 'A list of directories to scan within this repository separated by a space. (default=current directory)'
    required: false
    default: '.'
  plan-args:
    description: 'Terraform plan arguments'
    required: true
    default: ''
  env-id:
    description: 'Environment ID for Accurics to scan'
    required: true
    default: ''
  app-id:
    description: 'Accurics CLI Application Token ID'
    required: true
    default: ''
  repo:
    description: 'Repository Location'
    required: false
    default: '__empty__'
  url:
    description: 'Accurics Application URL'
    required: false
    default: 'https://app.accurics.com'
  fail-on-violations:
    description: 'Allows Accurics to fail the build when violations are found (default=true)'
    required: false
    default: true
  fail-on-all-errors:
    description: 'Allows Accurics to fail the build when any errors are encountered (default=true)'
    required: false
    default: true
outputs:
  env-name:
    echo "::set-output name=env-name::$env_name"
  num-violations:
    echo "::set-output name=num-violations::$num_violations"
  num-resources:
    echo "::set-output name=num-resources::$num_resources"
  high:
    echo "::set-output name=high::$high"
  medium:
    echo "::set-output name=medium::$medium"
  low:
    echo "::set-output name=low::$low"
  native:
    echo "::set-output name=native::$native"
  inherited:
    echo "::set-output name=inherited::$inherited"
  drift:
    echo "::set-output name=drift::$drift"
  iacdrift:
    echo "::set-output name=iacdrift::$iacdrift"
  clouddrift:
    echo "::set-output name=clouddrift::$clouddrift"
  has-errors:
    echo "::set-output name=has-errors::$has_errors"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.debug-mode }}
    - ${{ inputs.terraform-version }}
    - ${{ inputs.directories }}
    - ${{ inputs.plan-args }}
    - ${{ inputs.env-id }}
    - ${{ inputs.app-id }}
    - ${{ inputs.repo-name }}
    - ${{ inputs.url }}
    - ${{ inputs.fail-on-violations }}
    - ${{ inputs.fail-on-all-errors }}

